language: generic
dist: trusty
sudo: required

install:
- virtualenv ~/py35 -p /usr/bin/python3.5
- source ~/py35/bin/activate
- pip --version
- pip install -U pip
- pip --version
- pip install -r requirements.txt
- pip install cx_Freeze
script:
#Create linux release
- source ~/py35/bin/activate
- python build_deployable.py build
- tar -zcvf release.tar.gz -C build .
- rm build -Rf
#Create Windows release
- export DISPLAY=:99.0
- echo $WINEDLLOVERRIDES
- Xvfb $DISPLAY &
- sleep 3
#- wine64 msiexec /i  python-64.msi /qn TARGETDIR=c:\\\\Python-64
#- wine64 c:\\\\Python-64\\\\python.exe c:\\\\Python-64\\\\scripts\\\\pip.exe install -U pip
#- wine64 c:\\\\Python-64\\\\python.exe c:\\\\Python-64\\\\scripts\\\\pip.exe install cx_freeze
#- wine64 c:\\\\Python-64\\\\python.exe c:\\\\Python-64\\\\scripts\\\\pip.exe install -r requirements.txt
#- wine64 c:\\\\Python-64\\\\python.exe build_deployable.py bdist_msi
- ls -a
- ls build -a
before_script:
- wget https://www.python.org/ftp/python/3.4.4/python-3.4.4.amd64.msi --output-document=python-64.msi
before_install: 
- sudo add-apt-repository ppa:fkrull/deadsnakes -y
- sudo add-apt-repository ppa:ubuntu-wine/ppa -y
- sudo apt-get update -y
- sudo apt-get install --no-install-recommends xvfb python3.5 python3.5-dev libncurses5-dev wine -y
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
- sudo apt-get update
- sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono
- Xvfb $DISPLAY &

after_success: 
deploy:
  provider: releases
  api_key:
    secure: D0YvRKsZcRykiCKKISaxVMjecHdDJLUmus8sMXBTqWIIRggzhZDSDJ96N+7qNVSQPwnPrH12vPjBkWypkEHuJxD7U99nTigzBWcBkQgk19lUN4mCTia7NYlWGe/3t2DvMJUmKrLnZlUPHfGG3agJTvww8Zh6mewBwBS67GTtUjKHrnBC3lqSKhJhy9OgeHMMa5V4wklD39zI0Il1lDsMFVNdeN748vuyUhBqtwButeU3dlPE9ObzT42SKhSojGfWCVosPsLDDYCE3zS8flJutr7F4qdnU9uO9dPnW9pIrMN8aI9qbVCQREhAvBCAv4+jRFEo6RnjXYIzCnueCiY/UULShaLOdsQ6MBELUnuP65J6CFgyTuInzsPIyrNcXDUJnBSDmYzmNfP+79NFYbqgknldHREggSy7C7AHIu8QoklaIZbAHt+pkFfJUQ8cU7RsennatYSH1Pj2+X7PhQlTiVTDf4Wb6SdPY5I04wd+CXf5D3fmdvsPxMFdJ0+c3xf78IzCXNhSH7mtJbZkcvKBPG1McHPo6Knrd6fGbD8Ijizb35fVxMK0nWAUe6QIgcZ4TzXTx/Xc2ms+mQ+Le8dAMXegMOXwqyQLVOcpqTaeoqUb+pvursQkqUj7bfP/PcHEsdDf9qzTveMUJwlRfslu4Oko3gsi+okP3mqWNHR5/2s=
  skip_cleanup: true
  file: release.tar.gz
  on:
    repo: StefanRvO/PyJeopardy

