sudo: required

language: generic

arch:
  packages:
    -  wine
    -  xorg-server-xvfb
    -  base
    -  wget
    -  python
    -  expat
    -  bzip2
    -  gdbm
    -  openssl
    -  libffi
    -  zlib
    -  python-setuptools
    -  python-resumable-urlretrieve
    -  make
    -  base-devel


  script:
    - mknod -m 444 /dev/random c 1 8 || true
    - mknod -m 444 /dev/urandom c 1 9 || true
    - wget https://sourceforge.net/projects/winpython/files/WinPython_3.5/3.5.3.1/WinPython-32bit-3.5.3.1Zero.exe/download -O py35.exe
    - curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash
    - ~/.pythonz/bin/pythonz install 3.5.3 || true
    - cat ~/.pythonz/log/build.log
    #- pacaur -S python35 --noconfirm --noedit
    - virtualenv ~/py35 -p ~/.pythonz/pythons/CPython-3.5.3/bin/python3.5
    - source ~/py35/bin/activate
    - pip --version
    - pip install -U pip
    - pip --version
    - pip install -r requirements.txt
    - pip install cx_Freeze
    #Create linux release
    - source ~/py35/bin/activate
    - python build_deployable.py build
    - tar -zcvf release.tar.gz -C build .
    - rm build -Rf
    #Create Windows release
    - export DISPLAY=:99.0
    - export WINEDLLOVERRIDES="mscoree,mshtml="
    - echo $WINEDLLOVERRIDES
    - Xvfb $DISPLAY &
    - sleep 3
    - wine py35.exe /S /D=C:\py35
    - wine WinPython-32bit-3.5.3.1Zero/python-3.5.3/python.exe -m pip install -U pip
    - wine WinPython-32bit-3.5.3.1Zero/python-3.5.3/python.exe -m pip install setuptools
    - wine WinPython-32bit-3.5.3.1Zero/python-3.5.3/python.exe -m pip install cx_freeze
    - wine WinPython-32bit-3.5.3.1Zero/python-3.5.3/python.exe -m pip install -r requirements.txt
    - wine WinPython-32bit-3.5.3.1Zero/python-3.5.3/python.exe build_deployable.py bdist_msi
    - mv dist/*.msi release.msi
script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"



after_success: 
deploy:
  provider: releases
  api_key:
    secure: D0YvRKsZcRykiCKKISaxVMjecHdDJLUmus8sMXBTqWIIRggzhZDSDJ96N+7qNVSQPwnPrH12vPjBkWypkEHuJxD7U99nTigzBWcBkQgk19lUN4mCTia7NYlWGe/3t2DvMJUmKrLnZlUPHfGG3agJTvww8Zh6mewBwBS67GTtUjKHrnBC3lqSKhJhy9OgeHMMa5V4wklD39zI0Il1lDsMFVNdeN748vuyUhBqtwButeU3dlPE9ObzT42SKhSojGfWCVosPsLDDYCE3zS8flJutr7F4qdnU9uO9dPnW9pIrMN8aI9qbVCQREhAvBCAv4+jRFEo6RnjXYIzCnueCiY/UULShaLOdsQ6MBELUnuP65J6CFgyTuInzsPIyrNcXDUJnBSDmYzmNfP+79NFYbqgknldHREggSy7C7AHIu8QoklaIZbAHt+pkFfJUQ8cU7RsennatYSH1Pj2+X7PhQlTiVTDf4Wb6SdPY5I04wd+CXf5D3fmdvsPxMFdJ0+c3xf78IzCXNhSH7mtJbZkcvKBPG1McHPo6Knrd6fGbD8Ijizb35fVxMK0nWAUe6QIgcZ4TzXTx/Xc2ms+mQ+Le8dAMXegMOXwqyQLVOcpqTaeoqUb+pvursQkqUj7bfP/PcHEsdDf9qzTveMUJwlRfslu4Oko3gsi+okP3mqWNHR5/2s=
  skip_cleanup: true
  file:
    - release.tar.gz
    - release.msi
  on:
    repo: StefanRvO/PyJeopardy




