language: python
dist: trusty
matrix:
  include:
    - dist: xenial
      sudo: required
      os: linux
      env: TOXENV=xenial_wine
      install:
        - sudo add-apt-repository ppa:wine/wine-builds -y
        - sudo apt-get update 
        - sudo apt-get install --no-install-recommends -y winehq-devel xvfb
        #Windows
      script:
        - export DISPLAY=:99.0
        - export WINEDLLOVERRIDES="mscoree,mshtml="
        - echo $WINEDLLOVERRIDES
        - Xvfb $DISPLAY &
        - sleep 3
        - PYPREFIX=WinPython-32bit-3.5.3.1Zero/python-3.5.3
        - wget https://sourceforge.net/projects/winpython/files/WinPython_3.5/3.5.3.1/WinPython-32bit-3.5.3.1Zero.exe/download -O py35.exe
        - wine64 py35.exe /S /D=C:\py35
        - wine64 $PYPREFIX/python.exe -m pip install -U pip
        - wine64 $PYPREFIX/python.exe -m pip install setuptools
        - wine64 $PYPREFIX/python.exe -m pip install pyinstaller
        - wine64 $PYPREFIX/python.exe -m pip install -r requirements.txt
        - wine64 $PYPREFIX/Scripts/pyinstaller.exe PyJeopardy_Wine.spec
        - tar -zcvf $RELEASE_NAME  -C dist .
    - dist: trusty
      os: linux
      env: 
        - TOXENV=trusty
        - RELEASE_NAME=release_trusty.tar.gz
      python: 3.5

    - dist: precise
      sudo: required
      os: linux
      env: 
        - TOXENV=precise
        - RELEASE_NAME=release_precise.tar.gz
      python: 3.5

    - dist: xenial
      sudo: required
      os: linux
      env: 
        - TOXENV=xenial
        - RELEASE_NAME=release_xenial.tar.gz
      python: 3.5

    - dist: xenial
      services: docker
      os: linux
      env: 
        - TOXENV=archlinux
        - RELEASE_NAME=archlinux_precise.tar.gz
      install:
        - docker pull heichblatt/archlinux-yaourt
      script:
        - chmod +x arch_build.sh
        - docker run -it -v $(pwd):/travis --env="TOXENV=$TOXENV" heichblatt/archlinux-yaourt /bin/sh -c /travis/arch_build.sh

          
install:
    - pip install -r requirements.txt
    - pip install pyinstaller
    - sudo apt-get update 
    - sudo apt-get install --no-install-recommends -y openssl vlc

script:
  - pyinstaller PyJeopardy_Linux.spec
  - tar -zcvf $RELEASE_NAME -C dist .
after_success: 
deploy:
  provider: releases
  api_key:
    secure: D0YvRKsZcRykiCKKISaxVMjecHdDJLUmus8sMXBTqWIIRggzhZDSDJ96N+7qNVSQPwnPrH12vPjBkWypkEHuJxD7U99nTigzBWcBkQgk19lUN4mCTia7NYlWGe/3t2DvMJUmKrLnZlUPHfGG3agJTvww8Zh6mewBwBS67GTtUjKHrnBC3lqSKhJhy9OgeHMMa5V4wklD39zI0Il1lDsMFVNdeN748vuyUhBqtwButeU3dlPE9ObzT42SKhSojGfWCVosPsLDDYCE3zS8flJutr7F4qdnU9uO9dPnW9pIrMN8aI9qbVCQREhAvBCAv4+jRFEo6RnjXYIzCnueCiY/UULShaLOdsQ6MBELUnuP65J6CFgyTuInzsPIyrNcXDUJnBSDmYzmNfP+79NFYbqgknldHREggSy7C7AHIu8QoklaIZbAHt+pkFfJUQ8cU7RsennatYSH1Pj2+X7PhQlTiVTDf4Wb6SdPY5I04wd+CXf5D3fmdvsPxMFdJ0+c3xf78IzCXNhSH7mtJbZkcvKBPG1McHPo6Knrd6fGbD8Ijizb35fVxMK0nWAUe6QIgcZ4TzXTx/Xc2ms+mQ+Le8dAMXegMOXwqyQLVOcpqTaeoqUb+pvursQkqUj7bfP/PcHEsdDf9qzTveMUJwlRfslu4Oko3gsi+okP3mqWNHR5/2s=
  skip_cleanup: true
  file:
    - release_$TOXENV.tar.gz
#    - release.msi
  on:
repo: StefanRvO/PyJeopardy
