language: generic
dist: trusty

install:
- virtualenv ~/py35 -p /usr/bin/python3.5
- source ~/py35/bin/activate
- pip --version
- pip install -U pip
- pip --version
- pip install -r requirements.txt | pip install PyQt5==
- pip install cx_Freeze
script:
#Create linux release
- source ~/py35/bin/activate
- python build_deployable.py build
- tar -zcvf release.tar.gz -C build .
- rm build -Rf
#Create Windows release

- wine python-3.5.0.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 TargetDir="c:/python35" /nogui
- wine c:/python35/python.exe -m pip install -U pip
- wine c:/python35/python.exe -m pip install cx_freeze
- wine c:/python35/python.exe -m pip install -r requirements.txt
- wine c:/python35/python.exe build_deployable.py bdist_msi
- ls -a
before_script:
- wget https://www.python.org/ftp/python/3.5.0/python-3.5.0.exe
before_install: 
- sudo add-apt-repository ppa:fkrull/deadsnakes -y
- sudo apt-get update -y
- sudo apt-get install python3.5 python3.5-dev libncurses5-dev -y
- Xvfb $DISPLAY &

after_success: 
deploy:
  provider: releases
  api_key:
    secure: D0YvRKsZcRykiCKKISaxVMjecHdDJLUmus8sMXBTqWIIRggzhZDSDJ96N+7qNVSQPwnPrH12vPjBkWypkEHuJxD7U99nTigzBWcBkQgk19lUN4mCTia7NYlWGe/3t2DvMJUmKrLnZlUPHfGG3agJTvww8Zh6mewBwBS67GTtUjKHrnBC3lqSKhJhy9OgeHMMa5V4wklD39zI0Il1lDsMFVNdeN748vuyUhBqtwButeU3dlPE9ObzT42SKhSojGfWCVosPsLDDYCE3zS8flJutr7F4qdnU9uO9dPnW9pIrMN8aI9qbVCQREhAvBCAv4+jRFEo6RnjXYIzCnueCiY/UULShaLOdsQ6MBELUnuP65J6CFgyTuInzsPIyrNcXDUJnBSDmYzmNfP+79NFYbqgknldHREggSy7C7AHIu8QoklaIZbAHt+pkFfJUQ8cU7RsennatYSH1Pj2+X7PhQlTiVTDf4Wb6SdPY5I04wd+CXf5D3fmdvsPxMFdJ0+c3xf78IzCXNhSH7mtJbZkcvKBPG1McHPo6Knrd6fGbD8Ijizb35fVxMK0nWAUe6QIgcZ4TzXTx/Xc2ms+mQ+Le8dAMXegMOXwqyQLVOcpqTaeoqUb+pvursQkqUj7bfP/PcHEsdDf9qzTveMUJwlRfslu4Oko3gsi+okP3mqWNHR5/2s=
  skip_cleanup: true
  file: release.tar.gz
  on:
    repo: StefanRvO/PyJeopardy

addons:
  apt:
    packages:
      - wine
env:
  global:
    - DISPLAY=:99.0

