language: python
python:
    - 3.5
install:
    - pip install -r requirements.txt
    - pip install cx_Freeze

script:
  - python build_deployable.py build
  - tar -zcvf release.tar.gz -C build .
after_success:


# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
fast_finish: true
